### ISSUE TITLE
Clash-Meta Reality support

### ISSUE THREAD

**Issue by EbadiDev** [xcode75/XManagerPlus#251]
While examining the `subcontroller.php` `getMeta` function, I noticed that there is no code for the REALITY Protocol support. As I tested a configuration, I came across the following YAML code:
```yaml
- 
  name: 'Reality'
  type: vless
  server: 1.2.3.4
  port: 443
  uuid: uuid
  servername: updates.cdn-apple.com
  udp: true
  skip-cert-verify: false
```
However, this configuration appears to be incorrect. It should be formatted as follows:
```yaml
  -
    name: "Reality",
    type: vless,
    server: 1.2.3.4,
    port: 443,
    udp: true,
    uuid: uuid,
    tls: true,
    servername: updates.cdn-apple.com,
    flow: "xtls-rprx-vision",
    network: "tcp",
    reality-opts:{ "public-key": "DfuW50QGMg_7_GAcfV2W2pRrf_0zCn4d8SDWimQqkDE", "short-id": "d4dd377e"},
    client-fingerprint: "chrome"
```
In the updated YAML code, I made the necessary adjustments to align with the correct format.

EDITED 
 
Same for VMESS + HTTP Config it shouldn't be ```h2-opts``` it should be ```http-opts```: 
xmplus config : 
```yaml
 -
  name: 'vmess-http'
  type: vmess
  server: server
  port: 8880
  uuid: uuid
  alterId: 0
  cipher: auto
  udp: true
  skip-cert-verify: false
  network: http
  h2-opts: { method: GET, path: /, headers: { host: host.com, Host: host.com, Connection: keep-alive } }
```
expected config : 
```yaml
  - name: "vmess-http"
    type: vmess
    server: server
    port: 8880
    uuid: uuid
    alterId: 32
    cipher: auto
    # udp: true
    networkwork: http
    http-opts:
       method: "GET"
       path:
         - '/'
         - '/video'
       headers:
         Connection:
           - keep-alive
    # ip-version: ipv4 # 设置使用 IP 类型偏好，可选：ipv4，ipv6，dual，默认值：dual
```

Docs reference : [https://github.com/MetaCubeX/Clash.Meta/blob/Alpha/docs/config.yaml](https://github.com/MetaCubeX/Clash.Meta/blob/Alpha/docs/config.yaml)
