### ISSUE TITLE
SNI fragment issue

### ISSUE THREAD

**Issue by themealad** [xcode75/XManagerPlus#313]
hi 
please explain about SNI fragment 
i configured backend server for using SNI fragment like this :
```

      EnableFragment: true
      FragmentConfigs:
        Packets: "tlshello" # TLS Hello Fragmentation (into multiple handshake >
        Length: "100-200"   # minLength to maxLength
        Interval: "10-20"   # minInterval to maxInterval
```
But it dosnt work 

when i config the fragment manually in any application,it work like charm!

also i add the json code in security configration in xmplus panel like this:

```
{
  "serverName": "xxx.xxxxx.xx",
  "rejectUnknownSni": true,
  "allowInsecure": false,
  "fingerprint": "chrome",
  "sni": "xxx.xxxxx.xx",
  "flow": "none",
  "EnableFragment": true,
  "FragmentConfigs": {
    "Packets": "tlshello",
    "Length": "100-200",
    "Interval": "10-20"
  }
}
```
but it dosnt work again

please help
thanks for support
