### ISSUE TITLE
New Update Config

### ISSUE THREAD

**Issue by aliafshany** [xcode75/XManagerPlus#327]
Hello there

Would you mind please explaining about these new parameters in the config?
I couldn't find anything

```
      IPLimit:
        Enable: false # Enable the global ip limit of a user 
        RedisNetwork: tcp # Redis protocol, tcp or unix
        RedisAddr: 127.0.0.1:6379 # Redis server address, or unix socket path
        RedisUsername: default # Redis username
        RedisPassword: YOURPASSWORD # Redis password
        RedisDB: 0 # Redis DB
        Timeout: 5 # Timeout for redis request
        Expiry: 60 # Expiry time (second) 
```
