### ISSUE TITLE
The country flags not shown 

### ISSUE THREAD

**Issue by omiderfanmanesh** [xcode75/XManagerPlus#42]
The country flags are not shown in Clash but they are shown in the panel and user area in the website.

```
proxies:
 -
  name: '?? Spain-n-01'
  type: trojan
  server: mydomain
  port: 
  password: 
  sni: mydomain
  udp: true
  skip-cert-verify: false
  network: grpc
  grpc-opts: { grpc-service-name: mydomain }
```
