### ISSUE TITLE
failed to verify certificate 

### ISSUE THREAD

**Issue by letmefind** [xcode75/XManagerPlus#96]
Just tried out XMplus, Frontend deployed as explained in the instruction but the backend side does not get to work for some reason. 
Server OS: CentOS 7
dir: /etc/XMPlus/config.yml

```
Log:
  Level: warning # Log level: none, error, warning, info, debug
  AccessPath: # /etc/XMPlus/access.Log
  ErrorPath: # /etc/XMPlus/error.log
DnsConfigPath:  /etc/XMPlus/dns.json
RouteConfigPath: # /etc/XMPlus/route.json
InboundConfigPath: # /etc/XMPlus/inbound.json
OutboundConfigPath: # /etc/XMPlus/outbound.json
ConnectionConfig:
  Handshake: 8
  ConnIdle: 150
  UplinkOnly: 0
  DownlinkOnly: 0
  BufferSize: 64
Nodes:
    -
      ApiConfig:
        ApiHost: "https://XXXX.org"
        ApiKey: "ktAM1OQS6qdCwZr"
        NodeID: 4
        Timeout: 30
      ControllerConfig:
        UpdatePeriodic: 60
        CertConfig:
          Provider: cloudflare
          Email: author@xmplus.dev
          CertEnv:
            CLOUDFLARE_EMAIL: XXXXXX@gmail.com
            CLOUDFLARE_API_KEY: XXXXXX
```
           

xmplus log:

> Mar 09 12:10:40 XM-Server-VPN systemd[1]: Started XMPlus Service.
Mar 09 12:10:40 XM-Server-VPN XMPlus[10503]: XMPlus v2.1.0 (A custom version of XrayR)
Mar 09 12:10:40 XM-Server-VPN XMPlus[10503]: 2023/03/09 12:10:40 Starting XMPlus
Mar 09 12:10:40 XM-Server-VPN XMPlus[10503]: 2023/03/09 12:10:40 [Warning] core: Xray 1.7.3 started
Mar 09 12:10:40 XM-Server-VPN XMPlus[10503]: 2023/03/09 12:10:40.452977 ERROR RESTY Get "https://XXXXXX.org/api/v2/query/server/4?key=ktAM1OQS6qdCwZr": tls: failed to verify certificate: x509: certificate signed by unknown authority, Attempt 1
Mar 09 12:10:40 XM-Server-VPN XMPlus[10503]: 2023/03/09 12:10:40.606148 ERROR RESTY Get "https://XXXXXX.org/api/v2/query/server/4?key=ktAM1OQS6qdCwZr": tls: failed to verify certificate: x509: certificate signed by unknown authority, Attempt 2
Mar 09 12:10:40 XM-Server-VPN XMPlus[10503]: 2023/03/09 12:10:40.769732 ERROR RESTY Get "https://XXXXXX.org/api/v2/query/server/4?key=ktAM1OQS6qdCwZr": tls: failed to verify certificate: x509: certificate signed by unknown authority, Attempt 3
Mar 09 12:10:41 XM-Server-VPN XMPlus[10503]: 2023/03/09 12:10:41.039069 ERROR RESTY Get "https://XXXXXX.org/api/v2/query/server/4?key=ktAM1OQS6qdCwZr": tls: failed to verify certificate: x509: certificate signed by unknown authority, Attempt 4
Mar 09 12:10:41 XM-Server-VPN XMPlus[10503]: 2023/03/09 12:10:41 Get "https://XXXXXX.org/api/v2/query/server/4?key=ktAM1OQS6qdCwZr": tls: failed to verify certificate: x509: certificate signed by unknown authority
Mar 09 12:10:41 XM-Server-VPN XMPlus[10503]: 2023/03/09 12:10:41 XMPlus fialed to start: request https://XXXXXX.org/api/v2/query/server/4 failed: Get "https://XXXXXX.org/api/v2/query/server/4?key=ktAM1OQS6qdCwZr": tls: failed to verify certificate: x509: certificate signed by unknown authority
Mar 09 12:10:41 XM-Server-VPN XMPlus[10503]: panic: XMPlus fialed to start: request https://XXXXXX.org/api/v2/query/server/4 failed: Get "https://XXXXXX.org/api/v2/query/server/4?key=ktAM1OQS6qdCwZr": tls: failed to verify certificate: x509: certificate signed by unknown authority
Mar 09 12:10:41 XM-Server-VPN XMPlus[10503]: goroutine 1 [running]:
Mar 09 12:10:41 XM-Server-VPN XMPlus[10503]: log.Panicf({0x3107276?, 0x3565ab0?}, {0xc000b43e68?, 0xc000010af8?, 0x29d8c00?})
Mar 09 12:10:41 XM-Server-VPN XMPlus[10503]: log/log.go:391 +0x67
Mar 09 12:10:41 XM-Server-VPN XMPlus[10503]: github.com/xcode75/XMPlus/panel.(*Panel).Start(0xc0004ac240)
Mar 09 12:10:41 XM-Server-VPN XMPlus[10503]: github.com/xcode75/XMPlus/panel/panel.go:186 +0x3c5
Mar 09 12:10:41 XM-Server-VPN XMPlus[10503]: main.main()
Mar 09 12:10:41 XM-Server-VPN XMPlus[10503]: github.com/xcode75/XMPlus/main/main.go:93 +0x2bf
Mar 09 12:10:41 XM-Server-VPN systemd[1]: XMPlus.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 09 12:10:41 XM-Server-VPN systemd[1]: Unit XMPlus.service entered failed state.
Mar 09 12:10:41 XM-Server-VPN systemd[1]: XMPlus.service failed.

Any workaround to get fix this issue? have been trying to dig into this issue but no joy so far and no useful documentation found.
